language: go

go:
  - 1.8

install:
  - go get -t ./...
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

env:
  global:
    secure: "OG8RvTU36AxYSc3fsctPQkScWmrzLluwx"

script:
  - make test

after_success:
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci -repotoken $COVERALLS_TOKEN

notifications:
  email: false
