language: go

go:
  - 1.7

install:
  - go get -t ./...
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

env:
  global:
    secure: "VswWg0Bu9bkVmXZDg0paGJ6NFA5n4GYxM"

script:
  - make test

after_success:
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci -repotoken $COVERALLS_TOKEN

notifications:
  email: false
