language: go

go:
  - 1.13.8

env:
  - GO111MODULE=on

script:
  - env GO111MODULE=on make test

after_success:
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci

notifications:
  email: false