Simulation = "CollectiveAggregation"
Servers = 3
Bf = 2
Suite = "Ed25519"
Rounds = 1
RunWait = "24h"
Bandwidth = 1000

Hosts, NbrGroups, NbrGroupAttributes, NbrAggrAttributes, Proofs
3, 10, 2, 10, true