Simulation = "LocalClearAggregation"
Servers = 7
Bf = 2
Suite = "Ed25519"
Rounds = 1
RunWait = "24h"
Bandwidth = 1000

Hosts, NbrResponses, NbrGroups, NbrGroupAttributes, NbrWhereAttributes, NbrAggrAttributes, Proofs
7, 10, 10, 2, 2, 10, true
