Simulation = "LocalClearAggregation"
Servers = 7
Bf = 2
Rounds = 1
RunWait = 6000000
Bandwidth = 1000

Hosts, NbrResponses, NbrGroups, NbrGroupAttributes, NbrAggrAttributes, Proofs
7, 10, 10, 2, 10, true
