Simulation = "ServiceMedCo"
Servers = 3
Bf = 2
Rounds = 1
RunWait = 6000000
Bandwidth = 1000
Delay = 10
NbrGroupAttributes = [2,5]

Hosts, NbrDPs, NbrResponses, NbrGroupsClear, NbrGroupsEnc, NbrAggrAttributes, RandomGroups, DataRepetitions, Proofs
3, 3, 500, 0, 2, 10, true, 10, false
