Simulation = "ServiceMedCo"
Servers = 2
Bf = 2
Rounds = 1
RunWait = 6000000
Bandwidth = 100
Delay = 70
NbrGroupAttributes = [2,5]

Hosts, NbrDPs, NbrResponses, NbrGroupsClear, NbrGroupsEnc, NbrAggrAttributes, RandomGroups, DataRepetitions, Proofs
1, 1, 500, 0, 2, 10, true, 10, false
