Simulation = "ServiceMedCo"
Servers = 3
Bf = 2
Rounds = 1
RunWait = 6000000
Bandwidth = 1000
Delay = 10
NbrGroupAttributes = [2,5]

Hosts, NbrDPs, NbrResponsesTot, NbrResponsesFiltered, NbrGroupsClear, NbrGroupsEnc, NbrWhereClear, NbrWhereEncrypted, NbrAggrClear, NbrAggrEncrypted, Count, RandomGroups, DataRepetitions, Proofs
3, 3, 500, 0, 0, 2, 0, 0, 0, 10, false, true, 10, false
