Simulation = "ServiceMedCo"
Servers = 3
Bf = 2
Rounds = 1
RunWait = 6000000
Bandwidth = 1000
NbrGroupAttributes = [2,5,2]

Hosts, NbrDPs, NbrResponsesTot, NbrResponsesFiltered, NbrGroupsClear, NbrGroupsEnc, NbrWhereClear, NbrWhereEncrypted, NbrAggrClear, NbrAggrEncrypted, Count, RandomGroups, DataRepetitions, Proofs
3, 3, 300, 30, 0, 3, 0, 0, 0, 2, false, true, 1, false
