Simulation = "ServiceMedCoI2B2"
Servers = 3
Bf = 2
Rounds = 1
RunWait = 6000000
Bandwidth = 1000

Hosts, NbrDPs, NbrResponsesTot, NbrResponsesFiltered, NbrWhereClear, NbrWhereEncrypted, NbrAggrClear, NbrAggrEncrypted, Count, RandomGroups, DataRepetitions, Proofs, QueryMode
3, 3, 300, 50, 0, 2, 0, 2, true, false, 1, true, 0
