Simulation = "ProofsVerification"
Servers = 1
Bf = 2
Rounds = 1
RunWait = 6000000
Bandwidth = 1000


Hosts, NbrServers, NbrDPs, NbrResponses, NbrGroups, NbrGroupAttributes, NbrAggrAttributes
1, 3, 3, 20, 3, 5000, 5000
1, 3, 3, 20, 1, 5000, 5000
