Simulation = "ProofsVerification"
Servers = 1
Bf = 2
Suite = "Ed25519"
Rounds = 1
RunWait = 6000000
Bandwidth = 1000


Hosts, NbrServers, NbrDPs, NbrResponses, NbrGroups, NbrGroupAttributes, NbrAggrAttributes
1, 3, 3, 10, 2, 2, 10
