Simulation = "ServiceUnLynx"
Servers = 3
Bf = 2
Rounds = 1
RunWait = 6000000
Bandwidth = 1000
NbrGroupAttributes = [2,5]

Hosts, NbrDPs, NbrResponsesTot, NbrResponsesFiltered, NbrGroupsClear, NbrGroupsEnc, NbrWhereClear, NbrWhereEncrypted, NbrAggrClear, NbrAggrEncrypted, Count, RandomGroups, DataRepetitions, Proofs
3, 3, 50, 0, 0, 2, 0, 0, 0, 10, true, true, 1, false
