Simulation = "Shuffling"
Servers = 2
Bf = 2
Rounds = 1
RunWait = 6000000
Bandwidth = 1000

Hosts, NbrResponses, NbrGroupAttributes, NbrAggrAttributes, Proofs, PreCompute
2 , 15000, 2, 10, false, true
